"""
Generates the two pre-aggregated CSV files that power the Streamlit dashboard,
from your own local copy of the EM-DAT export.

Why this exists: EM-DAT's terms of use prohibit redistributing the database
(or a substantial part of it) publicly. This repo therefore never contains
the raw event-level file — instead, app.py reads two small aggregated
outputs generated by this script:

  - data/flood_agg.csv   Country x flood_type x year sums (damage, insured,
                          deaths, affected) plus the underlying event counts
                          behind each sum. Powers every tab except Extreme
                          Events.
  - data/top_events.csv  Europe's 30 costliest individual flood events (a
                          small curated ranking, not a database extract).
                          Powers the Extreme Events tab only.

Usage:
    1. Register for a free EM-DAT account at https://public.emdat.be
    2. Download the Excel export and save it as data/emdat_floods_europe.xlsx
       (this file is git-ignored — never commit it)
    3. Run: python scripts/generate_agg_data.py
    4. The two output CSVs land in data/ (also git-ignored locally, but you
       need them to run the dashboard on your own machine)

For the deployed app, these two CSVs are instead hosted privately (e.g.
Google Drive) and fetched at runtime via a URL configured in Streamlit
Cloud's Secrets — see README.md for the full deployment walkthrough.
"""

import os
import pandas as pd

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW_PATH = os.path.join(BASE, "data", "emdat_floods_europe.xlsx")
AGG_OUT = os.path.join(BASE, "data", "flood_agg.csv")
EVENTS_OUT = os.path.join(BASE, "data", "top_events.csv")
TOP_N_EVENTS = 30

COUNTRY_RENAME = {
    "United Kingdom of Great Britain and Northern Ireland": "UK",
    "Russian Federation": "Russia",
    "Bosnia and Herzegovina": "Bosnia",
    "Netherlands (Kingdom of the)": "Netherlands",
    "Republic of Moldova": "Moldova",
}


def main():
    if not os.path.exists(RAW_PATH):
        raise FileNotFoundError(
            f"Raw EM-DAT file not found at {RAW_PATH}.\n"
            "Register for free at https://public.emdat.be, download the "
            "Excel export, and save it at that exact path before running "
            "this script."
        )

    df = pd.read_excel(RAW_PATH, sheet_name="EM-DAT Data")
    cols = [
        "Country", "ISO", "Disaster Subtype", "Start Year", "Start Month",
        "Total Deaths", "Total Affected",
        "Total Damage, Adjusted ('000 US$)", "Insured Damage, Adjusted ('000 US$)",
    ]
    d = df[cols].copy()
    d.columns = [
        "country", "iso", "flood_type", "year", "month",
        "total_deaths", "total_affected", "total_damage_adj", "insured_damage_adj",
    ]
    d["country"] = d["country"].replace(COUNTRY_RENAME)

    # Marks events where BOTH damage and insured damage are recorded, needed
    # for the Insurance Gap tab's stricter matched subset (see app.py comments
    # for why this must be a joint condition, not two separate marginal sums).
    has_both = d["total_damage_adj"].notna() & d["insured_damage_adj"].notna()
    d["matched_damage"] = d["total_damage_adj"].where(has_both)
    d["matched_insured"] = d["insured_damage_adj"].where(has_both)

    agg = d.groupby(["country", "iso", "flood_type", "year"]).agg(
        n_events=("country", "size"),
        total_damage_adj=("total_damage_adj", lambda x: x.sum(min_count=1)),
        n_damage_events=("total_damage_adj", lambda x: x.notna().sum()),
        insured_damage_adj=("insured_damage_adj", lambda x: x.sum(min_count=1)),
        n_insured_events=("insured_damage_adj", lambda x: x.notna().sum()),
        matched_damage_adj=("matched_damage", lambda x: x.sum(min_count=1)),
        matched_insured_adj=("matched_insured", lambda x: x.sum(min_count=1)),
        n_matched_events=("matched_damage", lambda x: x.notna().sum()),
        total_deaths=("total_deaths", lambda x: x.sum(min_count=1)),
        n_death_events=("total_deaths", lambda x: x.notna().sum()),
        total_affected=("total_affected", lambda x: x.sum(min_count=1)),
        n_affected_events=("total_affected", lambda x: x.notna().sum()),
    ).reset_index()

    os.makedirs(os.path.dirname(AGG_OUT), exist_ok=True)
    agg.to_csv(AGG_OUT, index=False)
    print(f"Wrote {AGG_OUT} ({len(agg)} rows)")

    top_events = (
        d.dropna(subset=["total_damage_adj"])
        .nlargest(TOP_N_EVENTS, "total_damage_adj")
        [["country", "iso", "flood_type", "year", "month",
          "total_damage_adj", "insured_damage_adj", "total_deaths"]]
        .reset_index(drop=True)
    )
    top_events.to_csv(EVENTS_OUT, index=False)
    print(f"Wrote {EVENTS_OUT} ({len(top_events)} rows)")


if __name__ == "__main__":
    main()
